name: Deploy Product Service - Dev

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install PM2 globally
        run: npm install pm2 -g

      - name: Install dependencies
        run: npm ci
        working-directory: ./service

      - name: Run TypeScript checks
        run: npm run lint
        working-directory: ./service

      - name: Run Jest tests
        run: npm run test:ci
        working-directory: ./service
        env:
          NODE_ENV: test
          JWT_KEY: qemqekqenjkqneqhje

      - name: Build the project
        run: npm run build
        working-directory: ./service

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_DEV }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST_DEV }} >> ~/.ssh/known_hosts

      - name: Deploy and Reload PM2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER_DEV }}@${{ secrets.SSH_HOST_DEV }} << 'EOF'
            set -e
            REPO_DIR="/home/ebazaar/github/${{ github.repository }}"
            SERVICE_DIR="/home/ebazaar/github/${{ github.repository }}/service"
            if [ ! -d "$REPO_DIR" ]; then
              echo "Repository not found. Cloning..."
              git clone git@github.com:${{ github.repository }} $REPO_DIR
            else
              echo "Repository found. Pulling latest changes..."
              cd $REPO_DIR
              git pull
            fi
            cd $REPO_DIR
            git pull
            cd $SERVICE_DIR
            npm install
            npm run build
            if pm2 list | grep -q 'product'; then
              echo "Service is running. Reloading..."
              pm2 reload ecosystem.config.js --env development || { echo "PM2 reload failed"; pm2 logs; exit 1; }
            else
              echo "Service is not running. Starting..."
              pm2 start ecosystem.config.js --env development || { echo "PM2 start failed"; pm2 logs; exit 1; }
            fi

            echo "Deployment completed."
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_DEV }}
